export const marketTimingMarkets = [
  {
    id: "china",
    code: "CN",
    title: "中国股票",
    english: "CHINA EQUITIES",
    scope: "A股",
    status: "inherited",
    statusLabel: "原模型框架",
    description: "继承原 UI 的技术择时结构，后续重新接入实时行情并校正信号规则。",
    methods: [
      { id: "index-environment", name: "指数环境", status: "inherited", detail: "上证指数、深证成指、创业板指、北证50" },
      { id: "moving-average", name: "均线趋势", status: "inherited", detail: "MA60位置与MA5／MA10／MA20排列" },
      { id: "volume-ratio", name: "成交量比", status: "inherited", detail: "当日成交额 ÷ 前20日平均成交额" },
      { id: "candlestick", name: "K线形态", status: "inherited", detail: "上下影线、实体位置与量形联合验证" },
      { id: "momentum-20d", name: "20日动量", status: "inherited", detail: "最近20个交易日的价格变化" },
    ],
    nextSteps: ["确定行情指数代码", "接入前复权日线与成交额", "重新验证影线与量价规则"],
  },
  {
    id: "united-states",
    code: "US",
    title: "美国股票",
    english: "UNITED STATES EQUITIES",
    scope: "美股",
    status: "pending",
    statusLabel: "等待定义",
    description: "独立于A股择时模型，等待确定美国市场的指数基准、交易周期和信号阈值。",
    methods: [
      { id: "index-environment", name: "市场基准", status: "pending", detail: "指数与风险基准待确定" },
      { id: "moving-average", name: "趋势系统", status: "pending", detail: "均线周期与趋势规则待确定" },
      { id: "volume-ratio", name: "成交活跃度", status: "pending", detail: "成交量或成交额口径待确定" },
      { id: "price-action", name: "价格行为", status: "pending", detail: "K线与突破确认规则待确定" },
      { id: "momentum", name: "动量周期", status: "pending", detail: "观察周期和阈值待确定" },
    ],
    nextSteps: ["确定市场基准", "确定行情数据源", "定义美股专属择时规则"],
  },
];
